<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>ZF upload and progress bar example</title>

        <?php
        // add csss, jquery and jquery.progressbar
        $this->headLink()->appendStylesheet($this->baseUrl('/css/style.css'));
        $this->headScript()->appendFile($this->baseUrl('/js/jquery-1.4.4.min.js'));
        $this->headScript()->appendFile($this->baseUrl('/js/jquery.progressbar.js'));

        echo $this->headLink();
        echo $this->headScript();
        ?>
        
    </head>
    <body>
        <div>
            <?php echo $this->layout()->content ;?>            
        </div>
    </body>

</html>
